# <font color='blue'>Module 11 - CCPS 844 Data Mining</font>

# Neural network models (supervised)

## Classification

Class MLPClassifier implements a multi-layer perceptron (MLP) algorithm that trains using Backpropagation.

MLP trains on two arrays: array X of size (n_samples, n_features), which holds the training samples represented as floating point feature vectors; and array y of size (n_samples,), which holds the target values (class labels) for the training samples:

http://scikit-learn.org/stable/modules/neural_networks_supervised.html

**from sklearn.neural_network import MLPClassifier**

Warning This implementation is not intended for large-scale applications. In particular, scikit-learn offers no GPU  (Graphics Processing Unit) support. For much faster, GPU-based implementations, as well as frameworks offering much more flexibility to build deep learning architectures.

# Multi-layer Perceptron (MLP)

Multi-layer Perceptron (MLP) is a supervised learning algorithm that learns a function $$f(\cdot): R^m \rightarrow R^o$$ by training on a dataset, where m is the number of dimensions for input and o is the number of dimensions for output. Given a set of features $$X = {x_1, x_2, ..., x_m}$$ and a target y, it can learn a non-linear function approximator for either classification or regression. It is different from logistic regression, in that between the input and the output layer, there can be one or more non-linear layers, called hidden layers.

### The advantages of Multi-layer Perceptron are:

* Capability to learn non-linear models.
* Capability to learn models in real-time (on-line learning) using partial_fit.

#### The disadvantages of Multi-layer Perceptron (MLP) include:

* MLP with hidden layers have a non-convex loss function where there exists more than one local minimum. Therefore different random weight initializations can lead to different validation accuracy.
* **MLP requires tuning a number of hyperparameters such as the number of hidden neurons, layers, and iterations.**
* MLP is sensitive to feature scaling.

**Import the library**

In [1]:
from sklearn.neural_network import MLPClassifier

**Create a Dataset**

In [2]:
X = [[0., 0.], [1., 1.]]
y = [0, 1]

**Create an object of MLPClassifier**

In [3]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
# If the solver is ‘lbfgs’, the classifier will not use minibatch. When set to “auto”, batch_size=min(200, n_samples)

Init signature: MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', alpha=0.0001, batch_size='auto', learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
Docstring:     
Multi-layer Perceptron classifier.

This model optimizes the log-loss function using LBFGS or stochastic
gradient descent.

.. versionadded:: 0.18

Parameters
----------
**hidden_layer_sizes : tuple, length = n_layers - 2, default (100,)
    The ith element represents the number of neurons in the ith
    hidden layer.**

activation : {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
    Activation function for the hidden layer.

    - 'identity', no-op activation, useful to implement linear bottleneck,
      returns f(x) = x

    - 'logistic', the logistic sigmoid function,
      returns f(x) = 1 / (1 + exp(-x)).

    - 'tanh', the hyperbolic tan function,
      returns f(x) = tanh(x).

    - 'relu', the rectified linear unit function,
      returns f(x) = max(0, x)

solver : {'lbfgs', 'sgd', 'adam'}, default 'adam'
    The solver for weight optimization.

    - 'lbfgs' is an optimizer in the family of quasi-Newton methods.

    - 'sgd' refers to stochastic gradient descent.

    - 'adam' refers to a stochastic gradient-based optimizer proposed
      by Kingma, Diederik, and Jimmy Ba

    Note: The default solver 'adam' works pretty well on relatively
    large datasets (with thousands of training samples or more) in terms of
    both training time and validation score.
    For small datasets, however, 'lbfgs' can converge faster and perform
    better.

**alpha : float, optional, default 0.0001**
    L2 penalty (regularization term) parameter.

batch_size : int, optional, default 'auto'
    Size of minibatches for stochastic optimizers.
    If the solver is 'lbfgs', the classifier will not use minibatch.
    When set to "auto", `batch_size=min(200, n_samples)`

learning_rate : {'constant', 'invscaling', 'adaptive'}, default 'constant'
    Learning rate schedule for weight updates.

    - 'constant' is a constant learning rate given by
      'learning_rate_init'.

    - 'invscaling' gradually decreases the learning rate ``learning_rate_``
      at each time step 't' using an inverse scaling exponent of 'power_t'.
      effective_learning_rate = learning_rate_init / pow(t, power_t)

    - 'adaptive' keeps the learning rate constant to
      'learning_rate_init' as long as training loss keeps decreasing.
      Each time two consecutive epochs fail to decrease training loss by at
      least tol, or fail to increase validation score by at least tol if
      'early_stopping' is on, the current learning rate is divided by 5.

    Only used when ``solver='sgd'``.

learning_rate_init : double, optional, default 0.001
    The initial learning rate used. It controls the step-size
    in updating the weights. Only used when solver='sgd' or 'adam'.

power_t : double, optional, default 0.5
    The exponent for inverse scaling learning rate.
    It is used in updating effective learning rate when the learning_rate
    is set to 'invscaling'. Only used when solver='sgd'.

max_iter : int, optional, default 200
    Maximum number of iterations. The solver iterates until convergence
    (determined by 'tol') or this number of iterations. For stochastic
    solvers ('sgd', 'adam'), note that this determines the number of epochs
    (how many times each data point will be used), not the number of
    gradient steps.

shuffle : bool, optional, default True
    Whether to shuffle samples in each iteration. Only used when
    solver='sgd' or 'adam'.

**random_state : int, RandomState instance or None, optional, default None
    If int, random_state is the seed used by the random number generator;
    If RandomState instance, random_state is the random number generator;
    If None, the random number generator is the RandomState instance used
    by `np.random`.**

tol : float, optional, default 1e-4
    Tolerance for the optimization. When the loss or score is not improving
    by at least tol for two consecutive iterations, unless `learning_rate`
    is set to 'adaptive', convergence is considered to be reached and
    training stops.

verbose : bool, optional, default False
    Whether to print progress messages to stdout.

warm_start : bool, optional, default False
    When set to True, reuse the solution of the previous
    call to fit as initialization, otherwise, just erase the
    previous solution.

momentum : float, default 0.9
    Momentum for gradient descent update. Should be between 0 and 1. Only
    used when solver='sgd'.

nesterovs_momentum : boolean, default True
    Whether to use Nesterov's momentum. Only used when solver='sgd' and
    momentum > 0.

early_stopping : bool, default False
    Whether to use early stopping to terminate training when validation
    score is not improving. If set to true, it will automatically set
    aside 10% of training data as validation and terminate training when
    validation score is not improving by at least tol for two consecutive
    epochs.
    Only effective when solver='sgd' or 'adam'

validation_fraction : float, optional, default 0.1
    The proportion of training data to set aside as validation set for
    early stopping. Must be between 0 and 1.
    Only used if early_stopping is True

beta_1 : float, optional, default 0.9
    Exponential decay rate for estimates of first moment vector in adam,
    should be in [0, 1). Only used when solver='adam'

beta_2 : float, optional, default 0.999
    Exponential decay rate for estimates of second moment vector in adam,
    should be in [0, 1). Only used when solver='adam'

epsilon : float, optional, default 1e-8
    Value for numerical stability in adam. Only used when solver='adam'

Attributes
----------
classes_ : array or list of array of shape (n_classes,)
    Class labels for each output.

loss_ : float
    The current loss computed with the loss function.

coefs_ : list, length n_layers - 1
    The ith element in the list represents the weight matrix corresponding
    to layer i.

intercepts_ : list, length n_layers - 1
    The ith element in the list represents the bias vector corresponding to
    layer i + 1.

n_iter_ : int,
    The number of iterations the solver has ran.

n_layers_ : int
    Number of layers.

n_outputs_ : int
    Number of outputs.

out_activation_ : string
    Name of the output activation function.

Notes
-----
MLPClassifier trains iteratively since at each time step
the partial derivatives of the loss function with respect to the model
parameters are computed to update the parameters.

It can also have a regularization term added to the loss function
that shrinks model parameters to prevent overfitting.

This implementation works with data represented as dense numpy arrays or
sparse scipy arrays of floating point values.

References
----------
Hinton, Geoffrey E.
    "Connectionist learning procedures." Artificial intelligence 40.1
    (1989): 185-234.

Glorot, Xavier, and Yoshua Bengio. "Understanding the difficulty of
    training deep feedforward neural networks." International Conference
    on Artificial Intelligence and Statistics. 2010.

He, Kaiming, et al. "Delving deep into rectifiers: Surpassing human-level
    performance on imagenet classification." arXiv preprint
    arXiv:1502.01852 (2015).

Kingma, Diederik, and Jimmy Ba. "Adam: A method for stochastic
    optimization." arXiv preprint arXiv:1412.6980 (2014).
File:           c:\users\naeem\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py
Type:           ABCMeta

**Fit the model**

In [4]:
clf.fit(X, y)  

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

**After fitting (training), the model can predict labels for new samples:**

In [5]:
clf.predict([[2., 2.], [-1., -2.]])

array([1, 0])

**MLP can fit a non-linear model to the training data. clf.coefs_ contains the weight matrices that constitute the model parameters:**

In [6]:
[coef.shape for coef in clf.coefs_]

[(2, 5), (5, 2), (2, 1)]

In [7]:
clf.coefs_

[array([[-0.14196276, -0.02104562, -0.85522848, -3.51355396, -0.60434709],
        [-0.69744683, -0.9347486 , -0.26422217, -3.35199017,  0.06640954]]),
 array([[ 0.29164405, -0.14147894],
        [ 2.39665167, -0.6152434 ],
        [-0.51650256,  0.51452834],
        [ 4.0186541 , -0.31920293],
        [ 0.32903482,  0.64394475]]),
 array([[-4.53025854],
        [-0.86285329]])]

Currently, MLPClassifier supports only the Cross-Entropy loss function, which allows probability estimates by running the predict_proba method.

MLP trains using Backpropagation. More precisely, it trains using some form of gradient descent and the gradients are calculated using Backpropagation. For classification, it minimizes the Cross-Entropy loss function, giving a vector of probability estimates P(y|x) per sample x:

In [8]:
clf.predict_proba([[2., 2.], [1., 2.]]) 

array([[1.96718015e-04, 9.99803282e-01],
       [1.96718015e-04, 9.99803282e-01]])

In [9]:
clf.predict_proba([[2., 2.], [-1., -2.]]) 

array([[1.96718015e-004, 9.99803282e-001],
       [1.00000000e+000, 4.67017947e-144]])

 # multi-label classification
 
MLPClassifier (Multi-layer Perceptron Classifier) supports multi-class classification by applying Softmax as the output function.

Further, the model supports multi-label classification in which a sample can belong to more than one class. For each class, the raw output passes through the logistic function. Values larger or equal to 0.5 are rounded to 1, otherwise to 0. For a predicted output of a sample, the indices where the value is 1 represents the assigned classes of that sample:

**Create Data**

In [10]:
X = [[0., 0.], [1., 1.]]
y = [[0, 1], [1, 1]]

In [11]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(15,), random_state=1)

In [12]:
clf.fit(X, y)  

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(15,), random_state=1,
              solver='lbfgs')

In [13]:
clf.predict([[1., 2.]])

array([[1, 1]])

In [14]:
clf.predict([[0., 0.]])

array([[0, 1]])

## Tips on Practical Use

* Multi-layer Perceptron is sensitive to feature scaling, so it is highly recommended to scale your data. For example, scale each attribute on the input vector X to [0, 1] or [-1, +1], or standardize it to have mean 0 and variance 1. Note that you must apply the same scaling to the test set for meaningful results. You can use StandardScaler for standardization.

$$from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
#Don't cheat - fit only on training data
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
#apply same transformation to test data
X_test = scaler.transform(X_test) $$

An alternative and recommended approach is to use StandardScaler in a Pipeline

* Finding a reasonable regularization parameter \alpha is best done using GridSearchCV, usually in the range 10.0 ** -np.arange(1, 7).